#!/bin/sh
set -e

abs_path() {
    ruby -e 'puts File.expand_path(ARGV[0])' "$@"
}

topdir=`abs_path .`

# NB: You need hoe installed for this build to work
#jruby -S gem install --no-ri --no-rdoc hoe

mkdir -p pkg

# Build jdbc-derby
cd "$topdir"/drivers/derby
jruby -S rake gem
cp -f pkg/*.gem "$topdir/pkg/"

# Build infonium-activerecord-jdbcderby-adapter
cd "$topdir"/adapters/derby
jruby -S rake gem
cp -f pkg/*.gem "$topdir/pkg/"

# Build infonium-activerecord-jdbc-adapter
cd "$topdir"
jruby -S rake gem

